### ISSUE TITLE
How to launch it ?

### ISSUE THREAD

**Issue by lalebarde** [Nouuu/Docker-Projeqtor#2]
Hi Noé,
I have assumed to launch your project with `docker-compose up`, but I get this error:

```
[+] Running 0/0
 ⠿ Network nouuu_projeqtor_network  Error                                                                                                                              0.0s
failed to create network nouuu_projeqtor_network: Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```
Then if I do `docker swarm init`, it looks better:

```
Swarm initialized: current node (`hidden`) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token `hidden`

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

$ docker-compose up
[+] Running 1/0
 ⠿ Network nouuu_projeqtor_network  Created                                                                                                                            0.0s
external volume "" not found
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ docker-compose ps
NAME                COMMAND             SERVICE             STATUS              PORTS
```
Nothing seems to run. 

I am not a Docker expert. What is the way forward please?

**Comment by Official1111** [comment]
Hello 
I want to learn hacking 
Termux

**Comment by Nouuu** [comment]
Hi @lalebarde !

I should have specified that the given stack is for Docker Swarm, and not Docker compose. 
Your problem is because the network is of type "`overlay`", which is a swarm network (in case of docker compose only, it should be of type "`bridge`")

Your second issue on  `external volume "" not found` is more curious, look like volume name is empty i don't know why.

I am currently updating projeqtor image to last stable version 9.4.2, I will update my readme in the same time, watch for futher updates ! 😉
